[package]
name = "uip"
version.workspace = true
edition.workspace = true

[dependencies]
uip-core = { path = "../uip-core" }
uip-ingest = { path = "../uip-ingest" }
uip-api = { path = "../uip-api" }
uip-enrich = { path = "../uip-enrich" }
sqlx = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
